### ISSUE TITLE
How does Intl differ?

### ISSUE THREAD

**Issue by AutoSponge** [rthor/sort-international#3]
I was reading up on [Intl](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) and thought of you when I saw this (using the same array as your test):

```js
//tested in Chrome
var collator = new Intl.Collator('is-IS')
var arr = [
  'Jón Margeir Jónson', 'Fríður', 'Ægir', 'Friðgeir', 'Aron Sigurðsson', 'Ásmundur', '.DS_Store', 'Élgraður', 'Sólmundur', 'Aron Ómarsson', 'Aron Omarsson'
];
arr.sort(collator.compare);
//=> [".DS_Store", "Ægir", "Aron Omarsson", "Aron Ómarsson", "Aron Sigurðsson", "Ásmundur", "Élgraður", "Friðgeir", "Fríður", "Jón Margeir Jónson", "Sólmundur"]
```

This still differs from your test results. I think the reason is this:
```
Intl.Collator.supportedLocalesOf('es') //=> ["es"] runtime knows about Spanish
Intl.Collator.supportedLocalesOf('is') //=> [] runtime doesn't know Icelandic
```

So, I checked the [polyfill](https://github.com/andyearnshaw/Intl.js): 
> Providing an Intl.Collator implementation is no longer a goal of this project... 

:frowning:

**Comment by rthor** [comment]
Yeah, the internationalization API never seams to work—at least not the way you expect it to.

I don't know why it puts `Ægir` up top but it's at least not "correct" Icelandic sorting... Probably defaulting to some other comparator algorithm behind the scenes.
